name: ${project.name}
version: ${project.version} (Build ${git.commit.id.abbrev}, ${git.commit.time})
description: ${project.description}
main: com.parapvp.packetWrappersReloaded.PacketWrappersReloaded
author: Comphenix
authors: [Jaxon]